sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '%env(IMAGE_TAG)%'
        before_send: 'App\Service\Sentry\BeforeSendHandler'
        error_types: "E_ALL & ~E_NOTICE & ~E_DEPRECATED"
        integrations:
            - 'App\Configurator\Sentry\SentryIgnoreFromDefinition'
